name: Publish

on:
  release:
    types:
      - published

  # workflow dispatch for debug purposes only
  workflow_dispatch:
    inputs:
      release_tag:
        description: Expected release tag
        type: string
        required: true

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.validate_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - id: validate_version
        run: |
          tag_version=$(echo "${{ github.event.release.tag_name || inputs.release_tag }}" | awk 'sub(/^v/,"")1')
          package_version=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)

          if [[ ${tag_version} != ${package_version} ]] ; then
            echo "Invalid package version, expected ${tag_version}, got ${package_version}"
            exit 1
          fi

          echo "version=${tag_version}" >> $GITHUB_OUTPUT

  test-and-lint:
    name: test and lint
    needs: validate
    uses: ./.github/workflows/test-and-lint.yaml

  publish:
    name: publish
    needs:
      - validate
      - test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get publish info
        id: get_publish_info
        run: |
          version=${{ needs.validate.outputs.version }}
          pre=$(echo "${version}" | awk -F'[-.]' '{print $4; exit; }')
          is_dispatch=${{ github.event_name == 'workflow_dispatch' }}

          if [ -n "${pre}" ] ; then
            tag=$pre
          else
            tag=latest
          fi

          if ${is_dispatch} ; then
            mode=dry
          else
            mode=live
          fi

          {
            echo "### Publish"
            echo "| version | tag | mode |"
            echo "| - | - | - |"
            echo "| ${version} | ${tag} | ${mode} |"
          } >> $GITHUB_STEP_SUMMARY

          {
            echo "tag=${tag}"
            echo "mode=${mode}"
          } >> $GITHUB_OUTPUT

      - name: enable pnpm
        run: corepack enable pnpm

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: install and build
        run: pnpm install --frozen-lockfile && pnpm build

      - name: publish
        run: npm publish --access public --tag ${{ steps.get_publish_info.outputs.tag }}${{ steps.get_publish_info.outputs.mode == 'dry' && ' --dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{steps.get_publish_info.outputs.mode == 'dry' && 'INVALID TOKEN' || secrets.NPM_PUBLISH_TOKEN}}
