name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      dry_run:
        description: Run publish with --dry-run
        type: boolean
        default: true

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml

  publish:
    name: Publish
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - if: ${{ success() && !inputs.dry_run }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      - if: ${{ success() && inputs.dry_run }}
        run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
