name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      release_tag:
        description: Expected release tag
        type: string
        required: true

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml

  publish:
    name: Publish
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event == 'workflow_dispatch' }}
        run: echo "!! Running from workflow_dispatch is for debug only"

      - uses: actions/checkout@v4

      - run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - id: get_release_version
        run: |
          TAG_VERSION=$(echo "${{ github.event.release.tag_name || inputs.release_tag }}" | awk 'sub(/^v/,"")1')
          echo "version=${TAG_VERSION}" >> $GITHUB_OUTPUT

      - id: get_package_version
        run: |
          PACKAGE_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
          echo "version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - if: ${{ steps.get_release_version.outputs.version != steps.get_package_version.outputs.version }}
        run: |
          echo "Invalid package version, expected ${{ steps.get_release_version.outputs.version }}, got ${{ steps.get_package_version.outputs.version }}"
          exit 1

      - if: ${{ success() }}
        run: pnpm install --frozen-lockfile

      - if: ${{ success() }}
        run: pnpm build

      - if: ${{ success() && github.event == 'workflow_dispatch' }}
        run: npm publish --dry-run

      - if: ${{ success() && github.event_name == 'published' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
